# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e98db3d4766846f46b921da032c8db6a77d8280ea4726abd5fb9dfbfcbe0ad59965194f6208b102817c4abbb5c6ae561264f2b45533da7378247b1c860df439

test:
  secret_key_base: 4dbb3926d2eb3c83fb191ec7b72e07c4a3dc47f6f36787aafaeb898534195ea1e5c13939f879f3de2beead9753781c49a2f26fccf624c0433bebb9bd6c61f326

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
